# Generated by Django 5.2.11 on 2026-02-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='Sans sujet', max_length=200),
            preserve_default=False,
        ),
    ]
